use_default_settings: true
general:
  instance_name: "SearXNG"
  debug: false
server:
  secret_key: "change-me-to-random-string"
  bind_address: "0.0.0.0"
  port: 8080
  image_proxy: true
  limiter: true
search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
redis:
  url: "redis://valkey:6379/0"
